version: "3.9"
services:
 mslog:
    build:
      context: MsLog
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
 ms-shuffle-number:
  build:
    context: MsShuffle
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
  depends_on:
    - mslog

